version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DATABASE: 'water-divider'
  api:

    image: node:lts
    container_name: water-divider-api
    restart: always
    working_dir: /app
    volumes:
      [.:/app]
    ports:
      ["4000:4000"]
    environment:
      POSTGRES_USER: 'postgres'

      MARIADB_HOST: 'localhost' 
      MARIADB_PORT: 3306
      MARIADB_USERNAME: 'root'
      MARIADB_PASSWORD: 'mariadb'



    command: yarn server

