version: "3"

services:
  api:
    image: node:lts
    container_name: "api"
    restart: always
    depends_on:
      - postgres
      - mariadb
    ports:
      - "4000:4000"
  postgres:
    image: postgres:alpine3.19
    container_name: "postgres"
    restart: always
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST= localhost
      - POSTGRES_PORT= 3306
      - POSTGRES_USERNAME= mariadb
      - POSTGRES_PASSWORD= value
    ports:
      - "3306:3306"
  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: always
    volumes:
      - .:/app
    environment:
      MARIADB_HOST: localhost
      MARIADB_PORT: 3306
      MARIADB_USERNAME: root
      MARIADB_PASSWORD: mariadb
      MARIADB_ROOT_PASSWORD: "mariadb"